Задача 5

In [22]:
covers = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']})
covers

     cover
0  твердая
1   мягкая
2   мягкая
3  твердая
4  твердая
5   мягкая
6   мягкая

In [40]:
authors_price = pd.concat([authors_price, covers], axis = 1)
authors_price

   author_id author_name            book_totle  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [44]:
import numpy as np

temp = pd.pivot_table(authors_price, 
                      index = ['author_name'],
                      values = ['price'],
                      columns = ['cover'],
                      aggfunc = [np.sum],
                      fill_value = 0)
temp

               sum
             price
cover       мягкая твердая
author_name
Островский     660       0
Тургенев       650     450
Чехов            0     950